# Generated by Django 2.1.4 on 2021-12-29 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
